spring:
  datasource:
    url: jdbc:h2:mem:finlog;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always

  jpa:
    generate-ddl: false
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  h2:
    console:
      enabled: true

server:
  error:
    include-binding-errors: always
    include-message: always